services:
  ollama:
    container_name: ollama-prod
    image: ollama/ollama:latest
    ports:
      - "11434:11434" # Exposed for host access in production
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  zeroai_api:
    container_name: zeroai_api-prod
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ollama
    ports:
      - "3939:3939"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL_NAME=llama3.2:1b
      - PYTHONPATH=/app/src
    volumes:
      - ./src:/app/src
    entrypoint: /bin/bash -c "sleep 5 && curl -s http://ollama:11434/api/pull -d '{\"name\":\"llama3.1:8b\"}' && uvicorn API.api:app --host 0.0.0.0 --port 3939"

  zeroai_peer:
    container_name: zeroai_peer-prod
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ollama
    # No ports mapping to the host
    volumes:
      - ./src:/app/src
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - PYTHONPATH=/app/src
    working_dir: /app
    command: ["python3.11", "run/internal/start_peer_service_docker.py"]

volumes:
  ollama_data:
