version: '3.8'

services:
  zeroai:
    build: .
    container_name: zeroai_api-prod
    privileged: true  # Add this line
    ports:
      - "3939:3939"
    volumes:
      - .:/app
      - /var/cyford/zeroai/learning:/knowledge/internal_crew/agent_learning/self
      - ./knowledge:/app/knowledge
      - ./logs:/app/logs
      - /etc/cyford/zeroai/.env:/etc/cyford/zeroai/.env:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=http://ollama:11434
    env_file:
      - .env
      - /etc/cyford/zeroai/.env
    depends_on:
      - ollama
    restart: unless-stopped

  peer:
    build: .
    container_name: zeroai_peer-prod
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./knowledge:/app/knowledge
      - ./logs:/app/logs
      - /etc/cyford/zeroai/.env:/etc/cyford/zeroai/.env:ro
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=http://ollama:11434
    env_file:
      - .env
      - /etc/cyford/zeroai/.env
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: zeroai_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data: