services:
  zeroai-test:
      build: .
      container_name: zeroai_api-test
      ports:
        - "0.0.0.0:4949:3939"  # Different port to avoid conflict  : api
        - "0.0.0.0:444:333"    # Different port to avoid conflict :   web enterface
      volumes:
        - ./src:/app/src
        - ./API:/app/API
        - ./run:/app/run
        - ./config:/app/config
        - ./examples:/app/examples
        - /etc/cyford/zeroai/knowledge:/app/knowledge
        - ./logs:/app/logs
        - ./www:/app/www
        - /etc/cyford/zeroai/data:/app/data
        - /etc/cyford/zeroai/backup:/app/backup
        - ./tmp:/app/tmp
        - /etc/cyford/zeroai/.env:/app/.env:ro
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - PYTHONPATH=/app
        - OLLAMA_HOST=http://ollama-test:11434
        - LOCAL_UID=${LOCAL_UID}
        - LOCAL_GID=${LOCAL_GID}
      command: >
        bash -c "apt-get update && apt-get install -y docker.io && 
        mkdir -p /app/tmp && 
        service php8.4-fpm start && 
        nginx && 
        /app/venv/bin/gunicorn API.api:app --bind 0.0.0.0:3939 --worker-class uvicorn.workers.UvicornWorker --workers 2 --preload"
      privileged: true
      # env_file:
      #   - .env
      depends_on:
        - ollama-test
      restart: unless-stopped
      networks:
        - zeroai-test-network

  peer-test:
    build: .
    container_name: zeroai_peer-test
    ports:
      - "0.0.0.0:9090:8080"  # Different port to avoid conflict
    volumes:
      - ./src:/app/src
      - ./API:/app/API
      - ./run:/app/run
      - ./config:/app/config
      - ./examples:/app/examples
      - /etc/cyford/zeroai/knowledge:/app/knowledge
      - ./logs:/app/logs
      - ./www:/app/www
      - /etc/cyford/zeroai/data:/app/data
      - /etc/cyford/zeroai/backup:/app/backup
      - ./tmp:/app/tmp
      - /etc/cyford/zeroai/.env:/app/.env:ro
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=http://ollama-test:11434
      - LOCAL_UID=${LOCAL_UID}
      - LOCAL_GID=${LOCAL_GID}
    # env_file:
    #   - .env
    command: >
      bash -c "apt-get update && apt-get install -y docker.io && 
      mkdir -p /app/tmp && 
      /app/venv/bin/gunicorn API.persistent_crew_api:app --bind 0.0.0.0:8080 --worker-class uvicorn.workers.UvicornWorker --workers 2 --preload"
    privileged: true
    depends_on:
      - ollama-test
    restart: unless-stopped
    networks:
      - zeroai-test-network

  ollama-test:
    image: ollama/ollama:latest
    container_name: zeroai_ollama-test
    ports:
      - "0.0.0.0:12434:11434"  # Different port to avoid conflict
    volumes:
      - ollama_test_data:/root/.ollama
    restart: unless-stopped
    networks:
      - zeroai-test-network

volumes:
  ollama_test_data:

networks:
  zeroai-test-network:
    driver: bridge