# Use a non-root user for security
FROM python:3.11-slim

# Install dependencies for downloading Docker Compose, build essentials, and your utilities
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    nano \
    git \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

# --- Docker Compose Plugin Installation ---
# Add Docker's official GPG key
RUN install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
    && chmod a+r /etc/apt/keyrings/docker.gpg

# Add the Docker repository to Apt sources
RUN echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
    trixie stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install Docker Compose plugin
RUN apt-get update && apt-get install -y --no-install-recommends docker-compose-plugin \
    && rm -rf /var/lib/apt/lists/*

# Add this symbolic link for Docker compose to be discoverable
RUN mkdir -p /usr/local/lib/docker/cli-plugins \
    && ln -s /usr/bin/docker-compose-plugin /usr/local/lib/docker/cli-plugins/docker-compose
# --- End Docker Compose Plugin Installation ---

# Set the working directory
WORKDIR /app

# Install dependencies, leveraging build cache
COPY requirements.txt .

# Use a virtual environment to isolate dependencies
RUN python -m venv /opt/venv
# Activate the virtual environment
ENV PATH="/opt/venv/bin:$PATH"
# Install dependencies into the virtual environment
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Use Gunicorn as a process manager for Uvicorn in production
CMD ["gunicorn", "API.api:app", "--bind", "0.0.0.0:3939", "--worker-class", "uvicorn.workers.UvicornWorker", "--workers", "2", "--preload"]
