version: '3.8'

services:
  zeroai:
    build: .
    container_name: zeroai_api-prod
    ports:
      - "3939:3939"
    volumes:
      - ./knowledge:/app/knowledge
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=http://ollama:11434
    env_file:
      - /etc/cyford/zeroai/.env
      - .env
    depends_on:
      - ollama
    restart: unless-stopped

  peer:
    build: .
    container_name: zeroai_peer-prod
    ports:
      - "8080:8080"
    volumes:
      - ./knowledge:/app/knowledge
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=http://ollama:11434
    env_file:
      - /etc/cyford/zeroai/.env
      - .env
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: zeroai_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data: