# /app/src/crews/coding/tasks.py

from crewai import Task, Agent # <-- Add this import
from typing import Dict, Any

def create_coding_task(coder: Agent, inputs: Dict[str, Any]) -> Task:
    return Task(
        description=f"Generate code to fulfill the request: {inputs.get('topic')}. Context: {inputs.get('context')}.",
        expected_output='A well-commented code snippet',
        agent=coder
    )

def create_review_task(qa_engineer: Agent, inputs: Dict[str, Any]) -> Task:
    return Task(
        description="Review the code generated by the developer.",
        expected_output='A quality assurance report highlighting potential issues and improvements.',
        agent=qa_engineer
    )
