# model_config.yaml
llm_assignments:
  - crew: "Developer Crew"
    roles: ["Code Researcher", "Senior Developer", "QA Engineer"]
    models:
      - name: "codellama:13b"
        priority: "Best"
        description: "Specialized for code generation"
      - name: "llama3.1:8b"
        priority: "Next"
        description: "Strong generalist with good coding"
      - name: "llama3.2:latest"
        priority: "Fallback"
        description: "Capable generalist"
      - name: "llama3.2:1b"
        priority: "Slowest"
        description: "Lightweight, local fallback"

  - crew: "Research Crew"
    roles: ["Internal Research Agent"]
    models:
      - name: "llama3.1:8b"
        priority: "Best"
        description: "Powerful reasoning and analysis"
      - name: "llama3.2:latest"
        priority: "Next"
        description: "Strong generalist for research"
      - name: "gemma2:2b"
        priority: "Fallback"
        description: "Smaller, still capable for many research tasks"
      - name: "llama3.2:1b"
        priority: "Slowest"
        description: "Lightweight, local fallback"

  - crew: "Documentation Crew"
    roles: ["Documentation Agent"]
    models:
      - name: "llama3.2:latest"
        priority: "Best"
        description: "Strong language generation and summarization"
      - name: "llama3.1:8b"
        priority: "Next"
        description: "Good alternative for text generation"
      - name: "gemma2:2b"
        priority: "Fallback"
        description: "Efficient for text tasks"
      - name: "llama3.2:1b"
        priority: "Slowest"
        description: "Lightweight, local fallback"

  - crew: "DevOps Orchestrator"
    roles: ["DevOps Orchestrator Agent"]
    models:
      - name: "llama3.2:latest"
        priority: "Best"
        description: "Superior reasoning and task delegation"
      - name: "llama3.1:8b"
        priority: "Next"
        description: "Powerful alternative for orchestration"
      - name: "gemma2:2b"
        priority: "Fallback"
        description: "Capable of coordinating simpler tasks"
      - name: "llama3.2:1b"
        priority: "Slowest"
        description: "Lightweight, local fallback"

  - crew: "Repo Management Crew"
    roles: ["Repo Manager Agent"]
    models:
      - name: "llama3.2:latest"
        priority: "Best"
        description: "Well-rounded for general repo tasks"
      - name: "llama3.1:8b"
        priority: "Next"
        description: "Capable for standard instructions"
      - name: "gemma2:2b"
        priority: "Fallback"
        description: "Efficient for basic operations"
      - name: "llama3.2:1b"
        priority: "Slowest"
        description: "Lightweight, local fallback"