FROM python:3.9-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    ffmpeg \
    git \
    wget \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgomp1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements_sadtalker.txt .
#RUN pip install --no-cache-dir -r requirements_sadtalker.txt
RUN pip install  -r requirements_sadtalker.txt
# Copy avatar API
COPY avatar_api_sadtalker.py avatar_api.py

EXPOSE 7860

CMD ["python", "avatar_api.py"]